replicaCount: 1

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: webapprouting.kubernetes.azure.com   # AKS Application Routing ingress class
  host: nginx.example.com                         # change or leave blank for any host
