replicaCount: 1

image:
  repository: nginx:1.14.2
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: webapprouting.kubernetes.azure.com
  annotations: {}
  hosts: []
  tls: []

resources: {}
